# Generated by Django 5.1.2 on 2024-11-24 04:43

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airplane_image_file_path),
        ),
    ]
