# Generated by Django 5.1.2 on 2025-03-16 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_airplane_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
