# Generated by Django 5.1.2 on 2025-03-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_airport_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=400),
        ),
    ]
