# Generated by Django 5.1.2 on 2025-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_alter_airport_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='closest_big_city',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
